Repository NCIOCPL/drug-dictionary-app, pull requests merged in 2020-11, with the labels that each got.

#83 (#82) Title tag to include term name on definition page
  cypress/integration/TermPage.feature
  src/views/Definition/Definition.jsx
Labels: Needs Technical Review, Passed QA Review

#81 (#76) Fixes dropdown position based on screen
  cypress/integration/common/index.js
  src/components/atomic/Autocomplete/Autocomplete.jsx
  src/components/atomic/Autocomplete/Autocomplete.scss
  support/mock-data/drugdictionary/v1/Drugs/acenocoumarol.json
Labels: Needs Technical Review, Passed QA Review, Passed UX Review

#84 (#39) Autosuggest not displaying all suggestions
  src/components/molecules/search/Search.jsx
Labels: Needs Technical Review, Passed QA Review, Passed UX Review

#85 (#57) Updated autosuggest to not highlight first item
  src/components/atomic/Autocomplete/Autocomplete.jsx
  src/components/atomic/Autocomplete/__tests__/Autocomplete.tests.js
  src/components/molecules/search/__tests__/Search.test.js
Labels: Needs Technical Review, Passed UX Review

#86 (#80) Horizontal scroll appears for autosuggest on IE
  src/components/atomic/Autocomplete/Autocomplete.scss
Labels: Needs Technical Review, Passed QA Review

#92 (#91) Enable search from PageNotFound
  cypress/integration/SearchResults.feature
  src/views/ErrorBoundary/PageNotFound.jsx
Labels: Needs Technical Review, Passed QA Review
