Repository NCIOCPL/drug-dictionary-app, pull requests merged in 2020-09, with the labels that each got.

#21 (#3) Enabler: Create Search Box
  cypress/integration/AppAnalytics/SampleAnalyticsTest.feature
  cypress/integration/SearchBoxAndAutosuggest.feature
  cypress/integration/common/index.js
  src/App.js
  src/components/atomic/az-list/AZList.jsx
  src/components/atomic/az-list/AZList.scss
  src/components/atomic/az-list/__tests__/AZList.tests.js
  src/components/atomic/az-list/index.js
  src/components/index.js
  src/components/molecules/search-box/SearchBox.jsx
  src/components/molecules/search-box/SearchBox.scss
  src/components/molecules/search-box/__tests__/SearchBox.tests.js
  src/components/molecules/search-box/index.js
  src/components/molecules/search/Search.jsx
  src/components/molecules/search/Search.scss
  src/components/molecules/search/__tests__/Search.test.js
  src/components/molecules/search/__tests__/autoSuggestions.json
  src/components/molecules/search/index.js
  src/constants.js
  src/hooks/routing.js
  src/index.js
  src/services/api/actions/__tests__/getAutoSuggestResults.test.js
  src/services/api/actions/__tests__/getDrugSearchResults.test.js
  src/services/api/actions/__tests__/getSampleCallResults.test.js
  src/services/api/actions/getAutoSuggestResults.js
  src/services/api/actions/getDrugSearchResults.js
  src/services/api/actions/index.js
  src/services/api/axios-client.js
  src/services/api/endpoints.js
  src/services/api/requestInterceptors/requestHostInterceptor.js
  src/utils/strings.js
  src/views/Definition/Definition.jsx
  src/views/Definition/index.jsx
  src/views/index.js
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/%5B18.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/50%25.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/bev.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/beva.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/bin.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/2%2F3.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/bev.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/beva.json
  support/src/setupProxy.js
Labels: Needs Technical Review, Passed QA Review

#24 Term Page Display
  cypress/integration/TermPage.feature
  cypress/integration/common/MetaTags.js
  cypress/integration/common/index.js
  package-lock.json
  public/images/btn-patient-info.gif
  public/index.html
  src/components/atomic/SynonymTable/__tests__/synonym-table.tests.js
  src/components/atomic/SynonymTable/index.jsx
  src/components/atomic/SynonymTable/synonym-table.jsx
  src/components/atomic/SynonymTable/synonym-table.scss
  src/components/atomic/index.js
  src/components/index.js
  src/components/molecules/definitionitem/DefinitionItem.jsx
  src/components/molecules/definitionitem/DefinitionItem.scss
  src/components/molecules/definitionitem/__tests__/DefinitionItem.tests.js
  src/components/molecules/definitionitem/index.js
  src/components/molecules/search-box/SearchBox.scss
  src/components/molecules/search/Search.scss
  src/hooks/routing.js
  src/hooks/samples/UseCustomQuery.jsx
  src/index.js
  src/services/api/actions/__tests__/getAutoSuggestResults.test.js
  src/services/api/actions/__tests__/getDrugDefinition.test.js
  src/services/api/actions/__tests__/getDrugSearchResults.test.js
  src/services/api/actions/__tests__/getSampleCallResults.test.js
  src/services/api/actions/getDrugDefinition.js
  src/services/api/actions/getSampleCallResults.js
  src/services/api/actions/index.js
  src/services/api/endpoints.js
  src/styles/breakpoints.scss
  src/views/Definition/Definition.jsx
  support/mock-data/drugdictionary/v1/Drugs/750633.json
  support/mock-data/drugdictionary/v1/Drugs/801361.json
  support/mock-data/drugdictionary/v1/Drugs/bevacizumab.json
  support/mock-data/drugdictionary/v1/Drugs/search/Begins/acetic acid.json
  support/mock-data/drugdictionary/v1/Drugs/search/Begins/bevacizumab.json
  support/mock-data/drugdictionary/v1/Drugs/tretinoin.json
  support/mock-data/drugdictionary/v1/Drugs/xenogeneic-tyrosinase-dna-vaccine.json
  support/src/setupProxy.js
Labels: Needs QA Review, Needs Technical Review, Needs UX Review

#26 Conditional instrumentation for tests
  babel.config.js
  cypress/plugins/index.js
  package-lock.json
  package.json
Labels: Needs Technical Review

#32 (#31)Removed 'All' option from AZList
  src/components/atomic/az-list/AZList.jsx
Labels: Needs Technical Review

#29 (#27) patient information button
  cypress/integration/TermPage.feature
  cypress/integration/common/index.js
  src/components/molecules/definitionitem/DefinitionItem.jsx
  src/components/molecules/definitionitem/DefinitionItem.scss
Labels: Needs Technical Review, Passed QA Review, Passed UX Review

#30 (#13) Redirect to Pretty URL
  cypress/integration/PrettyUrlRedirect.feature
  cypress/integration/common/index.js
  src/views/Definition/Definition.jsx
  src/views/Definition/__tests__/Definition.PrettyURLRedirect.test.js
  support/mock-data/drugdictionary/v1/Drugs/acenocoumarol.json
Labels: Needs QA Review, Needs Technical Review, Passed UX Review

#35 (#28) Clinical Trials and Thesaurus links
  cypress/integration/TermPage.feature
  cypress/integration/common/index.js
  package-lock.json
  src/components/atomic/SynonymTable/synonym-table.scss
  src/components/molecules/definitionitem/DefinitionItem.jsx
  src/components/molecules/definitionitem/DefinitionItem.scss
  src/components/molecules/definitionitem/__tests__/DefinitionItem.tests.js
  src/views/Definition/Definition.jsx
Labels: Passed QA Review, Passed UX Review

#36 (#4) View Terms By Letter
  .pa11yci
  cypress/integration/AppAnalytics/ViewTermsByLetterAnalytics.feature
  cypress/integration/SearchBoxAndAutosuggest.feature
  cypress/integration/ViewTermsByLetter.feature
  cypress/integration/common/index.js
  package.json
  public/index.html
  src/App.js
  src/components/index.js
  src/components/molecules/TermList/__tests__/term-list-test.js
  src/components/molecules/TermList/index.js
  src/components/molecules/TermList/term-list.jsx
  src/components/molecules/TermListItem/__tests__/term-list-item.test.js
  src/components/molecules/TermListItem/index.js
  src/components/molecules/TermListItem/term-list-item.jsx
  src/components/molecules/TermListItem/term-list-item.scss
  src/constants.js
  src/services/api/actions/__tests__/getExpandCharResults.test.js
  src/services/api/actions/getExpandCharResults.js
  src/services/api/actions/index.js
  src/services/api/endpoints.js
  src/views/Terms/__tests__/terms.test.js
  src/views/Terms/index.js
  src/views/Terms/no-matching-results.jsx
  src/views/Terms/terms.jsx
  src/views/index.js
  support/mock-data/drugdictionary/v1/Drugs/795426.json
  support/mock-data/drugdictionary/v1/Drugs/expand/A.json
  support/mock-data/drugdictionary/v1/Drugs/expand/B.json
  support/mock-data/drugdictionary/v1/Drugs/expand/E.json
  support/mock-data/drugdictionary/v1/Drugs/expand/M.json
  support/mock-data/drugdictionary/v1/Drugs/macimorelin.json
  support/src/setupProxy.js
Labels: Needs Technical Review, Passed QA Review, Passed UX Review
