Repository NCIOCPL/drug-dictionary-app, pull requests merged in 2020-10, with the labels that each got.

#41 (#37) Analytics click event on PtInfo button
  cypress/integration/TermPage.feature
  cypress/integration/common/index.js
  src/components/molecules/definitionitem/DefinitionItem.jsx
  src/components/molecules/definitionitem/__tests__/DefinitionItem.tests.js
Labels: Needs QA Review, Needs Technical Review, Needs UX Review

#43 (#42) Synonym Table Order
  cypress/integration/AppAnalytics/ViewTermsByLetterAnalytics.feature
  src/components/atomic/SynonymTable/synonym-table.jsx
Labels: Needs Technical Review, Passed QA Review

#46 Task/45 appmodule support
  src/index.js
Labels: Needs Technical Review

#50 (#44) IE issues for Drug App
  src/components/atomic/SynonymTable/synonym-table.scss
  src/components/molecules/definitionitem/DefinitionItem.scss
  src/components/molecules/search-box/SearchBox.scss
Labels: Needs Technical Review, Needs UX Review

#49 (#15) Page Not Found 404
  .pa11yci
  cypress/integration/AppAnalytics/PageNotFoundAnalytics.feature
  cypress/integration/PageNotFound.feature
  cypress/integration/common/index.js
  src/views/Definition/Definition.jsx
  src/views/ErrorBoundary/ErrorBoundary.jsx
  src/views/ErrorBoundary/PageNotFound.jsx
Labels: Passed QA Review, Passed UX Review

#48 (#6) Dictionary Landing Page
  cypress/integration/AppAnalytics/SampleAnalyticsTest.feature
  cypress/integration/LandingPage.feature
  cypress/integration/SamplePageTest.feature
  cypress/integration/common/index.js
  src/views/Home/Home.jsx
  src/views/Home/__tests__/Home.en.test.js
  src/views/Home/__tests__/Home.test.js
  support/src/setupProxy.js
Labels: Needs Technical Review, Passed QA Review, Passed UX Review

#55 Bugfix: Clicking term causes page refresh
  src/components/molecules/TermList/__tests__/term-list-test.js
  src/components/molecules/TermList/term-list.jsx
  src/components/molecules/TermListItem/__tests__/term-list-item.test.js
  src/components/molecules/TermListItem/term-list-item.jsx
Labels: Needs Technical Review

#67 (#66) relocate fixtures for use with tests
  .eslintrc.js
  src/services/__tests__/buildAxiosRequest.test.js
  src/setupTests.js
  src/utils/fixtures.js
  src/utils/index.js
Labels: Needs Technical Review

#64 (#62) removed 'no results found' text
  src/components/molecules/search/Search.jsx
Labels: Needs Technical Review, Passed QA Review

#65 (#59) sorted synonym table contents
  src/components/atomic/SynonymTable/synonym-table.jsx
Labels: Passed QA Review, Passed UX Review

#72 (#58) scroll position at the top of a page
  src/views/Definition/Definition.jsx
  src/views/Definition/__tests__/Definition.test.js
  src/views/Terms/__tests__/terms.test.js
  src/views/Terms/terms.jsx
Labels: Needs Technical Review, Passed QA Review

#75 (#74) added effect to scroll to the top of a page
  src/views/SearchResults/SearchResults.jsx
  src/views/SearchResults/__tests__/SearchResults.test.js
Labels: Needs Technical Review

#77 (#51) Increase margin between h1 and intro text
  src/styles/app.scss
Labels: Passed UX Review

#73 (#40) Autosuggest Starts With Logic Update
  .pa11yci
  cypress/integration/SearchBoxAndAutosuggest.feature
  cypress/integration/common/index.js
  public/index.html
  src/components/atomic/Autocomplete/Autocomplete.scss
  src/components/molecules/search/Search.jsx
  src/components/molecules/search/__tests__/Search.test.js
  src/components/molecules/search/__tests__/autoSuggestions.json
  src/constants.js
  src/hooks/__tests__/autoSuggestQuery.test.js
  src/hooks/autoSuggestQuery.js
  src/hooks/index.js
  src/hooks/samples/UseAutoSuggestQuerySample.jsx
  src/services/api/actions/__tests__/getAutoSuggestResults.test.js
  src/services/api/actions/getAutoSuggestResults.js
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/%5B18.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/50%25.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugAlias/%5B18.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugAlias/50%25.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugAlias/bev.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugAlias/beva.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugAlias/bin.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugAlias/fg!.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugAlias/gle.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugTerm/%5B18.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugTerm/50%25.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugTerm/bev.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugTerm/beva.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugTerm/bin.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugTerm/fg!.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/DrugTerm/gle.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/bev.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/beva.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/bin.json
  support/mock-data/drugdictionary/v1/Autosuggest/Begins/gle.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/%5B18.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/50%25.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugAlias/%5B18.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugAlias/2%2F3.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugAlias/50%25.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugAlias/bev.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugAlias/beva.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugAlias/bin.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugAlias/fg!.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugAlias/gle.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugTerm/2%2F3.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugTerm/bev.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugTerm/beva.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/DrugTerm/bin.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/bin.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/fg!.json
  support/mock-data/drugdictionary/v1/Autosuggest/Contains/gle.json
  support/src/setupProxy.js
Labels: Needs Technical Review, Passed QA Review, Passed UX Review
